server:
  port: 9999
# Oracle Connect
spring:
  web:
    resources:
      static-locations: classpath:/static/
      static-path-pattern: /static/**
  profiles:
    active: local

  #File Size
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      
 
  datasource:
       driver-class-name: org.postgresql.Driver
       url: jdbc:postgresql://localhost:5432/choongsam
       username: postgres
       password: data
    


  # Jpa Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  # logger를 통해 하이버네이트 실행 SQL

  # View Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  mail:
    host: smtp.gmail.com
    port: 587
    username: jxxxmxxn@gmail.com
    password: vwqx ltmi lgiw slur
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true 
                 
  devtools:
    livereload:
      enabled: true          

#MyBatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org:
      hibernate:
        SQL: debug
        
#youtube api
youtube:
  api:
    key: "AIzaSyDB-l20C9L1cR8XYmyN9Olb-8TZ07ZPbd0"
    base-url: "https://www.googleapis.com/youtube/v3/"

file:
  base-path: C:/spring/springSrc17/choongsam_repo/src/main/webapp

