server:
  port: 9999
# Oracle Connect
spring:
  #File Size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
 
  datasource:
       driver-class-name: org.postgresql.Driver
       url: jdbc:postgresql://172.30.1.45:5432/choongSam
       username: master
       password: data
    


  # Jpa Setting
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  # logger를 통해 하이버네이트 실행 SQL

  # View Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  mail:
    host: smtp.gmail.com
    port: 587
    username: fantamasitta@gmail.com
    password: btdq swey iild bdzf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true 
                 
  devtools:
    livereload:
      enabled: true          

#MyBatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org:
      hibernate:
        SQL: debug
        
#youtube api
youtube:
  api:
    key: "AIzaSyDB-l20C9L1cR8XYmyN9Olb-8TZ07ZPbd0"
    base-url: "https://www.googleapis.com/youtube/v3/"

 
